/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vectores.pkg3;

import javax.swing.JOptionPane;

/**
 *
 * @author Payares
 */


public class interfazgrafica3 extends javax.swing.JFrame {

    /**
     * Creates new form interfazgrafica3
     */double v[];
     double v1[];
    public interfazgrafica3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmbcrear = new javax.swing.JButton();
        cmbLlenarManual = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lc = new javax.swing.JLabel();
        txtsuma = new javax.swing.JTextField();
        lk = new javax.swing.JLabel();
        txtresta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtLongitud2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLongitud1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 0, 36)); // NOI18N
        jLabel1.setText("Calculadora de vectores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Blackadder ITC", 0, 24))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbcrear.setBackground(new java.awt.Color(204, 255, 255));
        cmbcrear.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        cmbcrear.setText("Crear");
        cmbcrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmbcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, -1));

        cmbLlenarManual.setBackground(new java.awt.Color(204, 255, 255));
        cmbLlenarManual.setFont(new java.awt.Font("Blackadder ITC", 0, 14)); // NOI18N
        cmbLlenarManual.setText("Llenar vector");
        cmbLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLlenarManualActionPerformed(evt);
            }
        });
        cmbLlenarManual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbLlenarManualKeyTyped(evt);
            }
        });
        jPanel4.add(cmbLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, -1));

        cmbBorrar.setBackground(new java.awt.Color(204, 255, 255));
        cmbBorrar.setFont(new java.awt.Font("Blackadder ITC", 0, 14)); // NOI18N
        cmbBorrar.setText("Borrar");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, 200));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Blackadder ITC", 0, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lc.setText("La sumatoria es:");
        jPanel3.add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtsuma.setAutoscrolls(false);
        txtsuma.setEnabled(false);
        jPanel3.add(txtsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        lk.setText("La resta es:");
        jPanel3.add(lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));

        txtresta.setAutoscrolls(false);
        txtresta.setEnabled(false);
        jPanel3.add(txtresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Blackadder ITC", 0, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLongitud2.setBackground(new java.awt.Color(204, 255, 255));
        txtLongitud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud2ActionPerformed(evt);
            }
        });
        txtLongitud2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud2KeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, -1));

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jLabel2.setText("Longitud  #2 :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jLabel3.setFont(new java.awt.Font("Blackadder ITC", 0, 18)); // NOI18N
        jLabel3.setText("Longitud  #1:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 20));

        txtLongitud1.setBackground(new java.awt.Color(204, 255, 255));
        txtLongitud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitud1ActionPerformed(evt);
            }
        });
        txtLongitud1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitud1KeyTyped(evt);
            }
        });
        jPanel2.add(txtLongitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcrearActionPerformed
        // TODO add your handling code here:
        int Longitud;
        if(txtLongitud1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "digite la longitud #1","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();

        }
        if(txtLongitud2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "digite la longitud #2 ","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
        }
        else if (Integer.parseInt(txtLongitud1.getText().trim())==0){
            JOptionPane.showMessageDialog(this, " la longitud no puede ser 0 ","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
            txtLongitud1.selectAll();

        }
        else if (Integer.parseInt(txtLongitud2.getText().trim())==0){
            JOptionPane.showMessageDialog(this, " la longitud no puede ser 0 ","Error",JOptionPane.ERROR_MESSAGE);
               txtLongitud2.requestFocusInWindow();
            txtLongitud2.selectAll();
        }
        else{
            Longitud=Integer.parseInt(txtLongitud1.getText().trim() );
            v= new double [Longitud];
            Longitud=Integer.parseInt(txtLongitud2.getText().trim() );
            v1= new double [Longitud];
            JOptionPane.showMessageDialog(this, "Vector creado Exitosamente");

        }

    }//GEN-LAST:event_cmbcrearActionPerformed

    private void cmbLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLlenarManualActionPerformed
        // TODO add your handling code here:

        String res1,res2;

        double n1,n2,resta=0,suma1 =0,suma2=0,sumatotal=0;

       
        if(txtLongitud1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "digite la longitud del Vector #1 ","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud1.requestFocusInWindow();
        }
        

        else{
            for (int i = 0; i < v.length; i++) {
                n1= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite los elementos del vector #1 en la posicion"+i));
                v[i]=n1;
                suma1=suma1+n1;
            }
        }
            if(txtLongitud2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "digite la longitud del Vector#2 ","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud2.requestFocusInWindow();
            }
            else{
               for (int i = 0; i < v1.length; i++) {
              
                   n2= Double.parseDouble(JOptionPane.showInputDialog(this, "Digite los elementos del vector #2 en la posicion"+i));
                v1[i]=n2; 
             suma2=suma2+n2;
               }
               
            } 
               sumatotal=suma1+suma2;
                resta=suma1-suma2;
        
                

               
               
            
            res1 = String.valueOf(sumatotal);
           
            res2 =String.valueOf(resta);
            txtsuma.setText(res1);
            txtresta.setText(res2);

        
    }//GEN-LAST:event_cmbLlenarManualActionPerformed

    private void cmbLlenarManualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbLlenarManualKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbLlenarManualKeyTyped

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        txtsuma.setText("");
        txtresta.setText("");
       txtLongitud1.setText("");
        txtLongitud2.setText("");
        v = null;
        txtLongitud1.requestFocusInWindow();
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLongitud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud2ActionPerformed

    private void txtLongitud2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtLongitud2KeyTyped

    private void txtLongitud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitud1ActionPerformed

    private void txtLongitud1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitud1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtLongitud1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazgrafica3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbLlenarManual;
    private javax.swing.JButton cmbcrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lc;
    private javax.swing.JLabel lk;
    private javax.swing.JTextField txtLongitud1;
    private javax.swing.JTextField txtLongitud2;
    private javax.swing.JTextField txtresta;
    private javax.swing.JTextField txtsuma;
    // End of variables declaration//GEN-END:variables
}
